services:
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:8080/api
        VITE_GAME_URL: http://localhost:8080/game
        VITE_ROOT_URL: /
    working_dir: /app
    command: ["npm", "run", "build"]
    volumes:
      - ./frontend/dist:/app/dist

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://user:password@host.docker.internal:5432/pentale
    command: |
      sh -c "npm install &&
      pip install -r python/scraper/requirements.txt &&
      npx prisma generate &&
      npx prisma db push &&
      npx prisma db seed -- players"
    volumes:
      - ./backend:/app
    working_dir: /app

