version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:8080/api
        VITE_GAME_URL: http://localhost:8080/game
        VITE_ROOT_URL: /
    working_dir: /app
    command: ["npm", "run", "build"]
    volumes:
      - ./frontend/dist:/app/dist

  backend:
    build: ./backend
    environment:
      DATABASE_URL: "postgres://zane@host.docker.internal:5432/Pentale?schema=public&sslmode=disable"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: |
      sh -c "npm install &&
      npx prisma generate &&
      npx prisma db push &&
      node app.js"
    volumes:
      - ./backend:/app
    working_dir: /app
    networks:
      - my_docker_network  # ✅ attach to custom network
    ports:
      - "8080:8080"

networks:
  my_docker_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.99.0.0/16