name: Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-docker:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: Pentale
          POSTGRES_USER: zane
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
        
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Build containers
        run: docker-compose -f docker-compose.yml build

      - name: Start services
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: docker-compose -f docker-compose.yml up -d

      - name: Backend logs
        run: docker-compose logs backend

      - name: Wait for backend to be ready
        run: |
          for i in {1..10}; do
            echo "Attempt $i..."
            if curl -v --fail http://localhost:4000; then
              echo "Backend is ready!"
              exit 0
            fi
            echo "Waiting for backend... retrying in 3s"
            sleep 3
          done
      
          echo "❌ Backend failed to start. Printing logs:"
          docker-compose logs backend
          exit 1

      - name: Run Jest tests
        run: docker-compose -f docker-compose.yml run --rm backend npm test

        
      - name: Tear down
        run: docker-compose -f docker-compose.yml down -v
